spring:
  datasource:
    url: jdbc:mysql://localhost:3306/activitys?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=CTT
    username: root
    password: 12345678


  activiti:
#    设置流程引擎启动和关闭,为true时当数据库没有表会自动创建
    database-schema-update: true
#    关闭activiti自动部署 --> 使用流程部署器部署,不使用具体访问文件方式
    check-process-definitions: false

#logging:
#  level:
#   org.activiti.engine.impl.persistence.entity: debug
#  pattern:
#   console: '%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n'